export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#F6EEDC]">
      {/* Hero Section */}
      <section className="bg-[#7A1A14] text-white pt-32 sm:pt-36 pb-16 sm:pb-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <h1 className="font-royal text-3xl sm:text-4xl md:text-5xl text-[#D4AF37] mb-4 tracking-wide">
            Privacy Policy
          </h1>
          <p className="text-white/80 text-sm sm:text-base">
            Last updated: January 4, 2026
          </p>
        </div>
      </section>

      {/* Content Section */}
      <section className="max-w-4xl mx-auto px-4 sm:px-6 py-12 sm:py-16 lg:py-20">
        <div className="prose prose-lg max-w-none">
          
          {/* Introduction */}
          <div className="mb-8">
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="text-[#2A1E1A] leading-relaxed">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </div>

          {/* Interpretation and Definitions */}
          <div className="mb-8">
            <h2 className="font-royal text-2xl sm:text-3xl text-[#7A1A14] mb-4 tracking-wide">
              Interpretation and Definitions
            </h2>
            
            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-3 mt-6">
              Interpretation
            </h3>
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-3 mt-6">
              Definitions
            </h3>
            <p className="text-[#2A1E1A] leading-relaxed mb-3">
              For the purposes of this Privacy Policy:
            </p>

            <ul className="list-disc pl-6 space-y-3 text-[#2A1E1A] mb-6">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to <strong>Sandhya Foods</strong>, Plot No. 18, Baldev Nagar, Mata Ka Than Road, Magra Punjala, Jodhpur, Rajasthan 342001.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Rajasthan, India</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Website</strong> refers to Sandhya Foods, accessible from sandhyafoods.com</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </div>

          {/* Collecting and Using Personal Data */}
          <div className="mb-8">
            <h2 className="font-royal text-2xl sm:text-3xl text-[#7A1A14] mb-4 tracking-wide">
              Collecting and Using Your Personal Data
            </h2>
            
            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-3 mt-6">
              Types of Data Collected
            </h3>
            
            <h4 className="font-semibold text-lg text-[#7A1A14] mb-3 mt-4">
              Personal Data
            </h4>
            <p className="text-[#2A1E1A] leading-relaxed mb-3">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-[#2A1E1A] mb-6">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="font-semibold text-lg text-[#7A1A14] mb-3 mt-4">
              Usage Data
            </h4>
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              Usage Data is collected automatically when using the Service.
            </p>
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>
            <p className="text-[#2A1E1A] leading-relaxed">
              We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
            </p>
          </div>

          {/* Tracking Technologies */}
          <div className="mb-8">
            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-3">
              Tracking Technologies and Cookies
            </h3>
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
            </p>
            <p className="text-[#2A1E1A] leading-relaxed mb-3">
              We use both Session and Persistent Cookies for the purposes set out below:
            </p>
            <ul className="list-disc pl-6 space-y-4 text-[#2A1E1A] mb-6">
              <li>
                <strong>Necessary / Essential Cookies</strong><br/>
                Type: Session Cookies<br/>
                Administered by: Us<br/>
                Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.
              </li>
              <li>
                <strong>Cookies Policy / Notice Acceptance Cookies</strong><br/>
                Type: Persistent Cookies<br/>
                Administered by: Us<br/>
                Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
              </li>
              <li>
                <strong>Functionality Cookies</strong><br/>
                Type: Persistent Cookies<br/>
                Administered by: Us<br/>
                Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.
              </li>
            </ul>
          </div>

          {/* Use of Personal Data */}
          <div className="mb-8">
            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-3">
              Use of Your Personal Data
            </h3>
            <p className="text-[#2A1E1A] leading-relaxed mb-3">
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-[#2A1E1A] mb-6">
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
              <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
              <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
              <li>To manage Your requests: To attend and manage Your requests to Us.</li>
              <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
              <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns.</li>
            </ul>
          </div>

          {/* Retention */}
          <div className="mb-8">
            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-3">
              Retention of Your Personal Data
            </h3>
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
          </div>

          {/* Security */}
          <div className="mb-8">
            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-3">
              Security of Your Personal Data
            </h3>
            <p className="text-[#2A1E1A] leading-relaxed">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </div>

          {/* Children's Privacy */}
          <div className="mb-8">
            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-3">
              Children's Privacy
            </h3>
            <p className="text-[#2A1E1A] leading-relaxed">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>
          </div>

          {/* Changes to Policy */}
          <div className="mb-8">
            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-3">
              Changes to this Privacy Policy
            </h3>
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="text-[#2A1E1A] leading-relaxed">
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>
          </div>

          {/* Contact Us */}
          <div className="mb-8 bg-white p-6 sm:p-8 rounded-2xl border-2 border-[#D4AF37] shadow-lg">
            <h3 className="font-royal text-xl sm:text-2xl text-[#7A1A14] mb-4">
              Contact Us
            </h3>
            <p className="text-[#2A1E1A] leading-relaxed mb-4">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <div className="space-y-2 text-[#2A1E1A]">
              <p><strong>Company:</strong> Sandhya Foods</p>
              <p><strong>Phone:</strong> <a href="tel:+918005511786" className="text-[#7A1A14] hover:text-[#D4AF37] transition-colors">+91 80055 11786</a></p>
              <p><strong>Email:</strong> <a href="mailto:info@sandhyafoods.com" className="text-[#7A1A14] hover:text-[#D4AF37] transition-colors">info@sandhyafoods.com</a></p>
              <p><strong>Address:</strong> Plot No. 18, Baldev Nagar, Mata Ka Than Road, Magra Punjala, Jodhpur, Rajasthan 342001</p>
            </div>
          </div>

        </div>
      </section>
    </div>
  )
}